### 테스트 요청

GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.ybqSKPqGqZ7_zIBhaUhPvpO6VpHF0mzh0ebX23RUzI4

### Post 요청

POST http://localhost:8080/posts
Content-Type: application/json

{
  "title" : "test@test.com",
  "content": "1234"
}

### Post get 요청

GET http://localhost:8080/posts/1
Content-Type: application/json
