name: minog server CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  S3_BUCKET_NAME: minog-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build

      # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

      # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

      # zip 만들기
    - name: Make zip file
      run: zip -r ./minog.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_MINOG_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_MINOG_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./minog.zip s3://$S3_BUCKET_NAME/

      # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_MINOG_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_MINOG_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name minog-codeDeploy \
        --deployment-group-name minog-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=minog-deploy,bundleType=zip,key=minog.zip \ 
        --region ap-northeast-2
